# Generated by Django 4.1.3 on 2022-12-01 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userfollowing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
        migrations.DeleteModel(
            name='UserFollowing',
        ),
    ]
