# Generated by Django 4.1.3 on 2022-11-30 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
