# Generated by Django 4.1.3 on 2022-12-04 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_ingredient_recipes_recipe_ingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='quantity',
            options={'verbose_name': 'Quantity', 'verbose_name_plural': 'Quantities'},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='quantity',
            name='recipe',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='recipes.recipe'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='quantity',
            name='ingredient',
        ),
        migrations.AddField(
            model_name='quantity',
            name='ingredient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ingredient', to='recipes.ingredient'),
            preserve_default=False,
        ),
    ]
